version: "3"

services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: msql_project
    volumes:
      - mysql-data:/var/lib/mysql

  server:
    build:
      context: ./services
      dockerfile: ./Dockerfile
    container_name: server
    command: sh -c "./wait-for-it.sh -t 0 mysql:3306 --strict -- npm run start:prod"
    environment:
      APPHOST: localhost
      APPPORT: 7080
      DBHOST: mysql
      DBPORT: 3306
      DBUSERNAME: root
      DBPASSWORD: root
      DBNAME: msql_project
    # Debug use
    ports:
      - '8080:7080'
    depends_on:
      - mysql

volumes:
    mysql-data: